"""Remove category column from expenses table

Revision ID: 22ef277d914f
Revises: 82729d9ccfed
Create Date: 2025-12-31 02:05:48.951313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ef277d914f'
down_revision: Union[str, None] = '82729d9ccfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
