"""initial

Revision ID: 27634600babb
Revises: 
Create Date: 2025-04-30 22:22:13.821427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27634600babb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_budget', sa.Float(), nullable=False),
    sa.Column('currency_preference', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='ID подписки'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Ссылка на пользователя'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='Категория'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Цена'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='Валюта'),
    sa.Column('billing_period', sa.String(length=50), nullable=False, comment='Период оплаты'),
    sa.Column('next_payment', sa.DateTime(), nullable=False, comment='Следующий платеж'),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True, comment='Окончание пробного периода'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна?'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='Автопродление'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки'),
    sa.Column('logo_url', sa.String(length=512), nullable=True, comment='Ссылка на логотип'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False, comment='ID расхода'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Ссылка на пользователя'),
    sa.Column('subscription_id', sa.Uuid(), nullable=True, comment='Ссылка на подписку (опц.)'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Сумма'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='Валюта'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='Категория'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('subscriptions')
    op.drop_table('users')
    # ### end Alembic commands ###
