"""initial2

Revision ID: 463d10df4f7b
Revises: 27634600babb
Create Date: 2025-05-03 19:51:27.209816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '463d10df4f7b'
down_revision: Union[str, None] = '27634600babb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_links',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('websocket_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('notify_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_history.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='ID расхода',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на пользователя',
               existing_nullable=False)
    op.alter_column('expenses', 'subscription_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='Ссылка на подписку (опц.)',
               existing_nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Сумма',
               existing_nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Валюта',
               existing_nullable=False)
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата',
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='Описание')
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='Категория',
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='ID подписки',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на пользователя',
               existing_nullable=False)
    op.alter_column('subscriptions', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название',
               existing_nullable=False)
    op.alter_column('subscriptions', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='Категория',
               existing_nullable=False)
    op.alter_column('subscriptions', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Цена',
               existing_nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Валюта',
               existing_nullable=False)
    op.alter_column('subscriptions', 'billing_period',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Период оплаты',
               existing_nullable=False)
    op.alter_column('subscriptions', 'next_payment',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Следующий платеж',
               existing_nullable=False)
    op.alter_column('subscriptions', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment=None,
               existing_comment='Окончание пробного периода')
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Активна?',
               existing_nullable=False)
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Автопродление',
               existing_nullable=False)
    op.alter_column('subscriptions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               nullable=False,
               comment=None,
               existing_comment='Заметки')
    op.alter_column('subscriptions', 'logo_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               comment=None,
               existing_comment='Ссылка на логотип')
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата создания',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата создания',
               existing_nullable=False)
    op.alter_column('subscriptions', 'logo_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               comment='Ссылка на логотип')
    op.alter_column('subscriptions', 'notes',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               nullable=True,
               comment='Заметки')
    op.alter_column('subscriptions', 'auto_renew',
               existing_type=sa.BOOLEAN(),
               comment='Автопродление',
               existing_nullable=False)
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Активна?',
               existing_nullable=False)
    op.alter_column('subscriptions', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment='Окончание пробного периода')
    op.alter_column('subscriptions', 'next_payment',
               existing_type=postgresql.TIMESTAMP(),
               comment='Следующий платеж',
               existing_nullable=False)
    op.alter_column('subscriptions', 'billing_period',
               existing_type=sa.VARCHAR(length=50),
               comment='Период оплаты',
               existing_nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=8),
               comment='Валюта',
               existing_nullable=False)
    op.alter_column('subscriptions', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               comment='Цена',
               existing_nullable=False)
    op.alter_column('subscriptions', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment='Категория',
               existing_nullable=False)
    op.alter_column('subscriptions', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на пользователя',
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               comment='ID подписки',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment='Категория',
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='Описание')
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата',
               existing_nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               comment='Валюта',
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               comment='Сумма',
               existing_nullable=False)
    op.alter_column('expenses', 'subscription_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               comment='Ссылка на подписку (опц.)',
               existing_nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на пользователя',
               existing_nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               comment='ID расхода',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('notifications')
    op.drop_table('trial_notifications')
    op.drop_table('payment_history')
    op.drop_table('websocket_sessions')
    op.drop_table('telegram_links')
    # ### end Alembic commands ###
